server:
  port: 9998


spring:
  application:
    name: xa-consumer

  datasource:
    dynamic:
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xa?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xa2?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456
      primary: master      # 指定默认数据源名称

  shardingsphere:
    sharding:
      default-data-source-name: master
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/xa?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/xa2?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.10.20:8848
        namespace: c81acc96-1590-436d-a435-7b401eee54e4
